### ISSUE TITLE
Getting error when I use big file reader in bluemix node-red 

### ISSUE THREAD

**Issue by Ameritronik** [Jacques44/node-red-contrib-bigfile#3]
Hi,
I was able to include the big file reader in my app on bluemix. 
I downloaded my starter code, then added the following line in package.json:
    "node-red-contrib-bigfile":"1.1.0",
and pushed it back to blue mix. I was able to see the big file reader in the node-red editor.
When I try to deploy, I get the error message in the debug tab:

"5/2/2016, 10:38:50 PM2997ced5.fc4302
msg : error
TypeError: undefined is not a function"

How to solve the above issue?
Thanks

**Comment by Jacques44** [comment]
hello, thanks for your feedback. I'm having a look right now

**Comment by Jacques44** [comment]
I've pulled a fresh version of the node and made it work without any problem.
I've not any bluemix account right now but I'll check this evening.

Please did you use the node? When did you get this error message?

**Comment by Ameritronik** [comment]
Hi Jacques44,

I tried this again this morning and get the same error, listed below.
I have attached the node red-code with your big file included. I am not sure if I am using this
correctly.

Also in the recommended method for adding node, I followed the package.json update
but not the "add the required node package to the dependencies section"
Can you please tell me where the dependencies go?

May be the dependencies is the problem?

Here is what I am attempting to do:

(device to bluemix) Input is an MQTT  text message. The input text is provided to Text-To-Speech (TTS).
The TTS outputs audio in a unsigned-character-array. I am attempting to
break up this unsigned character-array into 1KB chunks to be returned via MQTT to device (bluemix-to-device).

You can see that I attempted ( rather pathetically :-) ) to generate an output format-er (Ofrmtr) to do the same 
or similar to your big file. But then I found your big file and attempted to use it..

Also the IBM's MQTT output node expects the msg.payload to be in json format. I assume the bigfile will
generate in json format right?

-------------------------------  IBM blue mix's recommended method to import nodes-------------------
Adding new nodes to the palette  There is a growing collection of additional nodes that can be added to the Node-RED editor. You can search for available nodes in the Node-RED library. Edit the file package.json and add the required node package to the dependencies section. The format is: "node-red-node-package-name":"x.x.x" Where x.x.x is the desired version number. 

----------------------------------- Node red error message--------------

5/3/2016, 7:50:43 AM9a72e17d.be10amsg : errorTypeError: undefined is not a function

--------- Original Message --------- Subject: Re: [Jacques44/node-red-contrib-bigfile] Getting error when I use big file reader in bluemix node-red (#3)

**Comment by Ameritronik** [comment]
Hi Jaques44,
A quick update:

I included the following files in package.json:
"byline":"4.2.1",
 "node-red-biglib":"1.1.0",
 "node-red-contrib-bigfile":"1.1.0",
 So now the dependencies are also pushed to blue mix, 
 but still same error  when I click on deploy button in node-red editor.  

---

--------- Original Message --------- Subject: RE: Re: [Jacques44/node-red-contrib-bigfile] Getting error when I use big file reader in bluemix node-red (#3)
From: hkanekal@ameritronik.com
Date: 5/3/16 8:06 am
To: "Jacques44/node-red-contrib-bigfile" reply@reply.github.com, "Jacques44/node-red-contrib-bigfile" node-red-contrib-bigfile@noreply.github.com

 Hi Jacques44,

I tried this again this morning and get the same error, listed below.
I have attached the node red-code with your big file included. I am not sure if I am using this
correctly.

Also in the recommended method for adding node, I followed the package.json update
but not the "add the required node package to the dependencies section"
Can you please tell me where the dependencies go?

May be the dependencies is the problem?

Here is what I am attempting to do:

(device to bluemix) Input is an MQTT  text message. The input text is provided to Text-To-Speech (TTS).
The TTS outputs audio in a unsigned-character-array. I am attempting to
break up this unsigned character-array into 1KB chunks to be returned via MQTT to device (bluemix-to-device).

You can see that I attempted ( rather pathetically :-) ) to generate an output format-er (Ofrmtr) to do the same 
or similar to your big file. But then I found your big file and attempted to use it..

Also the IBM's MQTT output node expects the msg.payload to be in json format. I assume the bigfile will
generate in json format right?

-------------------------------  IBM blue mix's recommended method to import nodes-------------------
Adding new nodes to the palette  There is a growing collection of additional nodes that can be added to the Node-RED editor. You can search for available nodes in the Node-RED library. Edit the file package.json and add the required node package to the dependencies section. The format is: "node-red-node-package-name":"x.x.x" Where x.x.x is the desired version number. 

----------------------------------- Node red error message--------------

5/3/2016, 7:50:43 AM9a72e17d.be10amsg : errorTypeError: undefined is not a function

--------- Original Message --------- Subject: Re: [Jacques44/node-red-contrib-bigfile] Getting error when I use big file reader in bluemix node-red (#3)

**Comment by Jacques44** [comment]
Hello, 
it's very strange. I've made a fresh install here and everything is perfect. I've another issue on bigcsv which seems the same as yours.

Is it possible for you to start node-red in verbose mode and tell me if you've more details?

Regards

**Comment by Jacques44** [comment]
Seems solved by upgrading node. Do you know which release of node you are using?

**Comment by Ameritronik** [comment]
Hi Jacques44,

This is what I have in my packages.json :
"byline":"4.2.1",
 "node-red-biglib":"1.1.0",
 "node-red-contrib-bigfile":"1.1.0",

But I decided to write my own big-file-type of code in one of the function nodes 
available on bluemix. I will probably use the bigfile reader later and try the latest version then,

Thank you for the follow up.

--------- Original Message --------- Subject: Re: [Jacques44/node-red-contrib-bigfile] Getting error when I use big file reader in bluemix node-red (#3)

**Comment by Jacques44** [comment]
You're welcome !
