### ISSUE TITLE
npm version not in sync

### ISSUE THREAD

**Issue by dceejay** [Jacques44/node-red-contrib-bigfile#4]
Hi,

the version of bigfile on npm  has line 81 of bigfile.js
    RED.nodes.registerType("bigfile reader",BigFileInNode); 
rather than
    RED.nodes.registerType("bigfile",BigFileInNode);

Can you update to be in sync ? - thanks

**Comment by Jacques44** [comment]
Hello

Sorry for that. I'll do that tonight CEST 

Regards

**Comment by dceejay** [comment]
which tonight ?

**Comment by Jacques44** [comment]
Done. I've made the change back to "bigfile reader" for compatibility 
I've made a slight change to documentation to make the example fully working

**Comment by dceejay** [comment]
Thanks !
