### ISSUE TITLE
Start and End options

### ISSUE THREAD

**Issue by saramcc1021** [Jacques44/node-red-contrib-bigfile#6]
I'm hoping to use the big file reader in a project I am working on to read in large files and stream the data to an executable.  Sometimes the data I need to read is to an updated file and in this case I only want to read the information added since the last read.  As such, I'm attempting to use the start and end config options but I am unable to get them to work.

This is an example of what I am passing into BigFile where startingLocation and endingLocation are integers:
{ filename: path, config: { flow: "buffer", start: _startingLocation_, end: _endingLocation_ } }

Setting these values seems to have no affect.  BigFile always returns the content of the entire file.

How can I set these values?

Thanks!

**Comment by Jacques44** [comment]
Hello, that works now
Regards
