### ISSUE TITLE
Keep msg objects

### ISSUE THREAD

**Issue by Mpercy-Git** [Jacques44/node-red-contrib-bigfile#8]
I've found your code much faster to load files but it seems to lose other objects I've added to the message. Can't seem to spot where the message gets supplanted in the code myself but I'm by no means a javascript expert. Any help is appreciated and thanks for the the node.

**Comment by Jacques44** [comment]
Hello, thanks. Yes this was a feature in order to keep the big nodes working together with no risk of control messages corruption.
But now, I've changed that in biglib 1.3.2. Now all messages are kept as is.

As biglib is a dependency, you would probably need to update it by hand

Regards

**Comment by Mpercy-Git** [comment]
Great thanks, I'll look at updating it.
