### ISSUE TITLE
Payload arguments are not being interpolated into the BigSSH node as expected

### ISSUE THREAD

**Issue by sethswango** [Jacques44/node-red-contrib-bigfile#9]
It appears the BigSSH node is broken. The connection is working fine, and I can execute commands that are written out fully as a string inside the node.

However, if I set "msg.payload = {"password":"123"}" and set the command to "echo ${payload.password}" then payload.password does not get parsed into the command. I hope this makes sense. I have attached screen shots.

 I am willing to donate $40 if you can address this. This is the only node that meets my needs. Feel free to email me at sethswangoauto@gmail.com

![Screenshot 2021-02-17 171943](https://user-images.githubusercontent.com/76489023/108281009-9d8e5e00-7144-11eb-9d45-428b42397842.png)
![Screenshot 2021-02-17 172016](https://user-images.githubusercontent.com/76489023/108281011-9e26f480-7144-11eb-84b7-ce310bc778e1.png)
![Screenshot 2021-02-17 172102](https://user-images.githubusercontent.com/76489023/108281012-9e26f480-7144-11eb-97a7-6efb95f5cb40.png)
![Screenshot 2021-02-17 172126](https://user-images.githubusercontent.com/76489023/108281014-9ebf8b00-7144-11eb-8ef1-189d8f1c58b6.png)

**Comment by Jacques44** [comment]
Hello,

Thanks for the proposal. :-) 

Is this you want to do?

![Screen Shot 2021-02-18 at 10 48 14](https://user-images.githubusercontent.com/18165555/108409558-ac4d4180-7226-11eb-9303-1fd6f99594fb.png)
![Screen Shot 2021-02-18 at 10 53 19](https://user-images.githubusercontent.com/18165555/108407516-1c0dfd00-7224-11eb-9f2a-c4a15281cc98.png)
![Screen Shot 2021-02-18 at 10 59 29](https://user-images.githubusercontent.com/18165555/108407521-1f08ed80-7224-11eb-8855-d0ab1d449d29.png)



The BigSSH node considers its command as a template when the payload is a json.



Templating is only available from the latest version. 
When I read all your details, I don’t see anything wrong in your configuration but maybe the BigSSH node release which should be 1.2.7 released 3 months ago.

As an advice, using ssh, you should set the full path for commands as usually, once connected, you won’t have your local profile loaded.

Please tell me if this is relevant to your problem and check it up?

Regards

**Comment by sethswango** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}

**Comment by Jacques44** [comment]
Aow my bad !

I didn't remember I had to check for update in https://flows.nodered.org/node/node-red-contrib-bigssh to make it available from the Palette !
That's really strange as all other nodes are up to date!

Sorry for wasting your time

You should update using the Palette now

**Comment by Jacques44** [comment]
Hello, hope it's working well now.
Love the idea of premium support. Added sponsor links
Regards

**Comment by Jacques44** [comment]
ok.
